# Copyright 2024 Tobijah.lu Inc. All Rights Reserved.
# Author: Tongjia Lu (lutonjia@163.com)
#

load(
    "//:build_config.bzl",
    "custom_cc_binary",
)

custom_cc_binary(
    name = "test",
    srcs = [
        "test.cc",
    ],
)
